### ISSUE TITLE
Editor cannot load invalid subcomponents

### ISSUE THREAD

**Issue by sillydan1** [DEIS-Tools/H-Uppaal#47]
**Summary:**
Deleting components that are referenced as subcomponents invalidates the model and results in bad loads.

**Steps to Reproduce:**

- Create a new project (File->New Project)
- Add two components (component1 and component2)
- [Save the project](https://github.com/DEIS-Tools/H-Uppaal/issues/45)
- Add component 2 as a subcomponent in component1
- Delete component2, but don't delete the subcomponent
- Save the project
- Close the editor
- Open the editor again

**Expected results:**
The editor loads the project, with an invalid subcomponent (preferably highlighted)

**Actual results:**
The editor does not load the project at all and logs the following error:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at dk.cs.aau.huppaal.HUPPAAL.updateDepthMap(HUPPAAL.java:394)
	at dk.cs.aau.huppaal.HUPPAAL.updateDepthMap(HUPPAAL.java:403)
	at dk.cs.aau.huppaal.HUPPAAL.deserializeProject(HUPPAAL.java:366)
	at dk.cs.aau.huppaal.HUPPAAL.initializeProjectFolder(HUPPAAL.java:282)
	at dk.cs.aau.huppaal.HUPPAAL.start(HUPPAAL.java:207)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:474)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by sillydan1** [comment]
Solved in https://github.com/DEIS-Tools/H-Uppaal/pull/50
